<?php

/**
 * @file
 * Contains fullcalendar_solr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function fullcalendar_solr_theme($existing, $type, $theme, $path) {
  return [
    'views_view__fullcalendar_solr_based_view' => [
      'template' => 'views-view--fullcalendar_solr_based_view',
      'variables' => []
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function fullcalendar_solr_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'fullcalendar_solr_based_view')) {
    $view->element['#attached']['library'][] = 'fullcalendar_solr/libraries.fullcalendar';
    $view->element['#attached']['library'][] = 'fullcalendar_solr/fullcalendar_solr';
  }
}

